import { getFlagUrl } from './flags'

export interface CountryOption {
  name: string // Full country name
  iso2: string // ISO 3166-1 alpha-2 country code
  flag: string // URL to the country flag image
}

export const COUNTRY_LIST: CountryOption[] = [
  { name: 'Turkey', iso2: 'tr', flag: getFlagUrl('tr') },
  { name: 'United Kingdom', iso2: 'gb', flag: getFlagUrl('gb') },
  { name: 'Germany', iso2: 'de', flag: getFlagUrl('de') },
  { name: 'France', iso2: 'fr', flag: getFlagUrl('fr') },
  { name: 'Italy', iso2: 'it', flag: getFlagUrl('it') },
  { name: 'Spain', iso2: 'es', flag: getFlagUrl('es') },
  { name: 'Portugal', iso2: 'pt', flag: getFlagUrl('pt') },
  { name: 'Netherlands', iso2: 'nl', flag: getFlagUrl('nl') },
  { name: 'Belgium', iso2: 'be', flag: getFlagUrl('be') },
  { name: 'Switzerland', iso2: 'ch', flag: getFlagUrl('ch') },
  { name: 'Austria', iso2: 'at', flag: getFlagUrl('at') },
  { name: 'Ireland', iso2: 'ie', flag: getFlagUrl('ie') },
  { name: 'Poland', iso2: 'pl', flag: getFlagUrl('pl') },
  { name: 'Czechia', iso2: 'cz', flag: getFlagUrl('cz') },
  { name: 'Denmark', iso2: 'dk', flag: getFlagUrl('dk') },
  { name: 'Norway', iso2: 'no', flag: getFlagUrl('no') },
  { name: 'Sweden', iso2: 'se', flag: getFlagUrl('se') },
  { name: 'Finland', iso2: 'fi', flag: getFlagUrl('fi') },
  { name: 'Iceland', iso2: 'is', flag: getFlagUrl('is') },
  { name: 'Russia', iso2: 'ru', flag: getFlagUrl('ru') },
  { name: 'Ukraine', iso2: 'ua', flag: getFlagUrl('ua') },
  { name: 'Romania', iso2: 'ro', flag: getFlagUrl('ro') },
  { name: 'Greece', iso2: 'gr', flag: getFlagUrl('gr') },
  { name: 'Hungary', iso2: 'hu', flag: getFlagUrl('hu') },
  { name: 'Bulgaria', iso2: 'bg', flag: getFlagUrl('bg') },
  { name: 'Croatia', iso2: 'hr', flag: getFlagUrl('hr') },
  { name: 'Serbia', iso2: 'rs', flag: getFlagUrl('rs') },
  { name: 'Slovakia', iso2: 'sk', flag: getFlagUrl('sk') },
  { name: 'Slovenia', iso2: 'si', flag: getFlagUrl('si') },

  { name: 'United States', iso2: 'us', flag: getFlagUrl('us') },
  { name: 'Canada', iso2: 'ca', flag: getFlagUrl('ca') },
  { name: 'Mexico', iso2: 'mx', flag: getFlagUrl('mx') },
  { name: 'Brazil', iso2: 'br', flag: getFlagUrl('br') },
  { name: 'Argentina', iso2: 'ar', flag: getFlagUrl('ar') },
  { name: 'Chile', iso2: 'cl', flag: getFlagUrl('cl') },
  { name: 'Colombia', iso2: 'co', flag: getFlagUrl('co') },
  { name: 'Peru', iso2: 'pe', flag: getFlagUrl('pe') },
  { name: 'Uruguay', iso2: 'uy', flag: getFlagUrl('uy') },
  { name: 'Paraguay', iso2: 'py', flag: getFlagUrl('py') },

  { name: 'Australia', iso2: 'au', flag: getFlagUrl('au') },
  { name: 'New Zealand', iso2: 'nz', flag: getFlagUrl('nz') },

  { name: 'Japan', iso2: 'jp', flag: getFlagUrl('jp') },
  { name: 'China', iso2: 'cn', flag: getFlagUrl('cn') },
  { name: 'Hong Kong', iso2: 'hk', flag: getFlagUrl('hk') },
  { name: 'Taiwan', iso2: 'tw', flag: getFlagUrl('tw') },
  { name: 'South Korea', iso2: 'kr', flag: getFlagUrl('kr') },
  { name: 'North Korea', iso2: 'kp', flag: getFlagUrl('kp') },
  { name: 'India', iso2: 'in', flag: getFlagUrl('in') },
  { name: 'Pakistan', iso2: 'pk', flag: getFlagUrl('pk') },
  { name: 'Bangladesh', iso2: 'bd', flag: getFlagUrl('bd') },
  { name: 'Sri Lanka', iso2: 'lk', flag: getFlagUrl('lk') },
  { name: 'Nepal', iso2: 'np', flag: getFlagUrl('np') },
  { name: 'Thailand', iso2: 'th', flag: getFlagUrl('th') },
  { name: 'Vietnam', iso2: 'vn', flag: getFlagUrl('vn') },
  { name: 'Malaysia', iso2: 'my', flag: getFlagUrl('my') },
  { name: 'Singapore', iso2: 'sg', flag: getFlagUrl('sg') },
  { name: 'Indonesia', iso2: 'id', flag: getFlagUrl('id') },
  { name: 'Philippines', iso2: 'ph', flag: getFlagUrl('ph') },

  { name: 'United Arab Emirates', iso2: 'ae', flag: getFlagUrl('ae') },
  { name: 'Qatar', iso2: 'qa', flag: getFlagUrl('qa') },
  { name: 'Saudi Arabia', iso2: 'sa', flag: getFlagUrl('sa') },
  { name: 'Kuwait', iso2: 'kw', flag: getFlagUrl('kw') },
  { name: 'Oman', iso2: 'om', flag: getFlagUrl('om') },
  { name: 'Bahrain', iso2: 'bh', flag: getFlagUrl('bh') },
  { name: 'Israel', iso2: 'il', flag: getFlagUrl('il') },
  { name: 'Iran', iso2: 'ir', flag: getFlagUrl('ir') },

  { name: 'Egypt', iso2: 'eg', flag: getFlagUrl('eg') },
  { name: 'Morocco', iso2: 'ma', flag: getFlagUrl('ma') },
  { name: 'Tunisia', iso2: 'tn', flag: getFlagUrl('tn') },
  { name: 'Algeria', iso2: 'dz', flag: getFlagUrl('dz') },
  { name: 'South Africa', iso2: 'za', flag: getFlagUrl('za') },
  { name: 'Nigeria', iso2: 'ng', flag: getFlagUrl('ng') },
  { name: 'Kenya', iso2: 'ke', flag: getFlagUrl('ke') },
  { name: 'Ethiopia', iso2: 'et', flag: getFlagUrl('et') },
  { name: 'Ghana', iso2: 'gh', flag: getFlagUrl('gh') },
  { name: 'Tanzania', iso2: 'tz', flag: getFlagUrl('tz') },
]
